def encode_preamble(ref_timestamp: int, timestamp_format: str, timezone: str) -> bytearray:
    ...

def encode_message_and_timestamp_delta(timestamp_delta: int, msg: bytes) -> bytearray:
    ...

def encode_message(msg: bytes) -> bytearray:
    ...

def encode_timestamp_delta(timestamp_delta: int) -> bytearray:
    ...
